version: "3.7"

services:
  Sandbox-Client-Master:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 5000:5000
      - 8080:8080
    container_name: Sandbox-Client-Master
    volume:
      - jenkins_home:/var/jenkins_sandbox_cm_home

  Development-Client-Master:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 5010:5000
      - 8090:8080
    container_name: Development-Client-Master
    volume:
      - jenkins_home:/var/jenkins_dev_cm_home
