version: "3.7"

services:
  Sandbox-Client-Master:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 5000:5000
      - 8080:8080
    container_name: Sandbox-Client-Master
    volumes:
      - ./jenkins_sandbox_cm_home:/var/jenkins_sandbox_cm_home

  Development-Client-Master:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 5010:5000
      - 8090:8080
    container_name: Development-Client-Master
    volumes:
      - ./jenkins_dev_cm_home:/var/jenkins_dev_cm_home

  Build-Agent-1:
    image: ubuntu:latest
    privileged: true
    user: root
    ports:
      - 22:22
    container_name: Build-Agent-1
